### ISSUE TITLE
Hacı bu script çalışmıyor

### ISSUE THREAD

**Issue by HafizBeyy** [metwse/rofi-tdk.sh#4]
`$ sudo sh Downloads/rofi-tdk.sh 
Downloads/rofi-tdk.sh: 50: Bad substitution
`
@metwse

**Comment by metwse** [comment]
hocam `bash` ile çalıştırın: `bash ~/Downloads/rofi-tdk.sh`
ya da `chmod +x rofi-tdk.sh` ile scripti yürütülebilir yaptıktan sonra direkt `~/Downloads/rofi-tdk.sh` ile çalıştırabilirsiniz.

**Comment by HafizBeyy** [comment]
reiz şimdi de `root@anan-ass:/var# bash rofi-tdk.sh 
Ön bellek yükleniyor.
rofi-tdk.sh: line 28: -sorting-method: command not found
`
 @metwse

**Comment by metwse** [comment]
```bash
metw@metw:~$ rofi -version
Version: 1.7.3
```
`rofi`nin güncel versiyonunu kullandığınızdan emin olun. -sorting-method, eski versiyonlarda çalışmıyor.

Yine olmazsa `bash` versiyonunuzu atabilir misiniz?
```bash
metw@metw:~$ bash -version
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
```

**Comment by HafizBeyy** [comment]
bruh patladık hocam kusura bakmayın `Command 'rofi' not found, but can be installed with:
sudo apt install rofi
`
