### ISSUE TITLE
Windiwrs te nasıl indirilir?

### ISSUE THREAD

**Issue by ocesta** [metwse/rofi-tdk.sh#5]
Linux için indirme yolunu anlatmışsınız ama windows için anlatılmamış.

**Comment by metwse** [comment]
hocam bu script linux'taki `rofi` yazılımıyla çalışmak için tasarlandı. windows'a wsl ile `rofi` belki kurulabilir. windows 11 kullanıyorsanız windows subsystem for linux'u indirip orada çalıştırmayı deneyebilirsiniz. indirdiğiniz linux subsysteminde de `rofi` paketini indirerek (mesela ubuntu'da indirmek için `sudo apt install rofi`) deneyebilirsiniz.
